### PR TITLE
Configurable spawn options for each mob

### PR DESCRIPTION
**Pull request by oversword**
Made redundant by https://github.com/BlockySurvival/mobs_animal_pack/pull/5

### CODE REVIEW

**Comment by oversword** [comment]
flux I'm not sure how to submit the comparable MR for mobs_animal, here it is https://github.com/oversword/mobs_animal/pull/1

**Comment by oversword** [comment]
For tracking:
https://github.com/NathanSalapat/desert_life/pull/2
https://github.com/oversword/mobs_animal/pull/1
https://github.com/oversword/mob_horse/pull/1
https://github.com/BlockySurvival/mobs_animal_pack/pull/2

**Comment by fluxionary** [comment]
1. never create a global variable that's not the name of the mod. i know not all mods obey this rule, but most of those that don't are older than the rule.
2. I'm not really sure what you changed here except to move the mob parameters into separate file named "config". This doesn't actually make things more configurable, it's still requiring a change in the source code to tweak values. did you intend to add a way to read these values from `minetest.settings`? 
3. variable names are way too long and redundant. instead of e.g. `global_mobs_animal_pack_mobs_turtles.spawn_on_turtle`, maybe something like `mobs.turtle.spawn_on`

**Comment by oversword** [comment]
1. I'm doing that to ensure it's unique, some mods already have one declared but don't use it, and if they do I don't want to interfere with anything... I can change it but it may have side effects
2. That's the point, you don't commit the config, you just get a copy on first pull - this makes sharing them harder however, but you could just have the config file import a file from a settings repo that you can commit. I have no idea what minetest.settings is, I'll look it up, do you have an example of a mod that uses that for config?
3. That's because I originally made a single config for the whole pack before realising it's split up :/ This is also consistent with the other changes I've made, notably mobs_animal, which does have a single config file. Doing it this way means the different structures can be merged later if the mod pack grows to include other animals, it also accounts for when a mod provides more than one animal. On the user config end this isn't an issue, it's just a longer name in code, the brief names are what they were before (for the mods that had them), I'm confident the naming structure is required for clarity, though the names of the globals should be addressed as per point 1.

**Comment by fluxionary** [comment]
>     1. I'm doing that to ensure it's unique, some mods already have one declared but don't use it, and if they do I don't want to interfere with anything... I can change it but it may have side effects

The standard is to only create maybe one global, which shares the name of the mod. If another mod isn't abiding by that standard, that's their problem, unless it's a major mod that's been around for ages. 

>     2. That's the point, you don't commit the config, you just get a copy on first pull - this makes sharing them harder however, but you could just have the config file import a file from a settings repo that you can commit. I have no idea what minetest.settings is, I'll look it up, do you have an example of a mod that uses that for config?

if you're looking to make my life easier, this is the opposite way to do it. i worked really hard to get all custom changes out of our local mod code repos on the server, and everything custom is done via the core config file (which you access through minetest.settings) or via monkey patching from our server's main custom mod. 

>     3. That's because I originally made a single config for the whole pack before realising it's split up :/ This is also consistent with the other changes I've made, notably mobs_animal, which does have a single config file. Doing it this way means the different structures can be merged later if the mod pack grows to include other animals, it also accounts for when a mod provides more than one animal. On the user config end this isn't an issue, it's just a longer name in code, the brief names are what they were before (for the mods that had them), I'm confident the naming structure is required for clarity, though the names of the globals should be addressed as per point 1.

the fact that mobs_animal_pack is a modpack and not a mod, reflects a choice i made to reduce the amount of work i'd do. if you want to refactor everything into a single mod, that might make things way saner, but you'd have to do it in a way that makes future maintenance easier. 

note that you can do things like the following, which avoids creating globals in secondary files:

```
result1, result2 = dofile("foo.lua")
print(result2) -- prints 8
--------------
-- in foo.lua
return 1, 3+5
```

honestly, there are so many major things wrong w/ our mobs, that minor clean up isn't really going to get us much. i suppose my main point, though, is that this PR (MR) gives us nothing, except a bunch of long variable names. 

i'm sorry if this is a bit harsh; i like teaching people how to more effectively contribute, but i'm feeling particularly unwell, and feel annoyed at myself as much as anything, that i can't explain what's needed and why this PR isn't currently useful.

**Pull request closed without merging**
